name: ROI
channels:
  - defaults
dependencies:
  - ca-certificates=2023.08.22
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.8.18
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - contourpy==1.1.1
      - cycler==0.12.1
      - editdistance==0.6.2
      - efficientnet==1.0.0
      - essential-generators==1.0
      - fonttools==4.46.0
      - h5py==3.10.0
      - imageio==2.33.1
      - imgaug==0.4.0
      - importlib-resources==6.1.1
      - keras-applications==1.0.8
      - keras-ocr==0.9.3
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - matplotlib==3.7.4
      - networkx==3.1
      - numpy==1.24.4
      - opencv-python==4.8.1.78
      - packaging==23.2
      - pillow==10.1.0
      - pyclipper==1.3.0.post5
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pywavelets==1.4.1
      - scikit-image==0.21.0
      - scipy==1.10.1
      - shapely==2.0.2
      - six==1.16.0
      - tifffile==2023.7.10
      - tqdm==4.66.1
      - validators==0.22.0
      - zipp==3.17.0
