name: myenv
channels:
  - defaults
dependencies:
  - python=3.9
  - pip:
      - html5lib==1.1
      - scikit-learn==1.3.2
      - imutils==0.5.4
      - Pillow==9.5.0
      - tensorflow==2.13.0
      - wfdb==3.4.1
      - keras==2.13.1
      - beautifulsoup4==4.12.2
      - imageio==2.9.0
      - imgaug==0.4.0
      - matplotlib
      - numpy==1.24.3
      - opencv_python==4.6.0.66
      - pandas==1.4.1
      - requests==2.21.0
      - scikit-image==0.20.0
      - scipy==1.9.1
      - seaborn==0.12.2
      - validators==0.18.2
      - spacy==3.0.8
      - https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_sm-0.4.0.tar.gz
